apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: chadev-demo
    spec:
      containers:
      - name: failing-http-server
        image: quay.io/robertjscott/failing-http-server:0.1.0
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          periodSeconds: 1
          timeoutSeconds: 1
